<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <ProjectReference Include="..\ECommerce-Clean-Arch.Domain\ECommerce-Clean-Arch.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="AutoMapper" Version="16.0.0" />
        <PackageReference Include="FluentValidation" Version="12.1.1" />
        <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
        <PackageReference Include="MediatR" Version="14.0.0" />
        <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.25" />
    </ItemGroup>

    <ItemGroup>
        <Folder Include="Abstractions\" />
        <Folder Include="Categories\Commands\" />
    </ItemGroup>

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <RootNamespace>ECommerce_Clean_Arch.Application</RootNamespace>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

</Project>